package com.charliehustle.services;

import java.io.IOException;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.healthmarketscience.jackcess.Row;
import com.healthmarketscience.jackcess.Table;

@Service
public class AccessDatabaseService {

    public void deleteRow(Table rosterTable, Row row)
       throws IOException
    {
        rosterTable.deleteRow(row);
    }

    public void updateRow(Table rosterTable,
                          Row row,
                          Map<String, String> columnValues) throws IOException {

            for(Map.Entry<String, String> mapEntry : columnValues.entrySet()){
                row.put(mapEntry.getKey(), mapEntry.getValue());
            }
            rosterTable.updateRow(row);
    }

    public void addRowFantasyBaseball(Table rosterTable, Map<String, String> playerDataUpdateMap) throws IOException {
        System.out.println("playerName " + playerDataUpdateMap.get("NAME") + " here");
        rosterTable.addRow(
           playerDataUpdateMap.get("OP"),
           playerDataUpdateMap.get("#"),
           playerDataUpdateMap.get("NAME"),
              null,
           playerDataUpdateMap.get("Team"),
           playerDataUpdateMap.get("Hand"),
           playerDataUpdateMap.get("Position"),
           playerDataUpdateMap.get("Age"),
           "ZZ",
           null,
           null,
           null,
           null,
           playerDataUpdateMap.get("MLB Overall Rank"),
           playerDataUpdateMap.get("MLB Organizational Rank"),
           playerDataUpdateMap.get("Platoon"));
    }

    public void addRowUfcFighter(Table rosterTable, Map<String, String> playerDataUpdateMap) throws IOException {
        System.out.println("fighter " + playerDataUpdateMap.get("Fighter_Name"));
        rosterTable.addRow(
                playerDataUpdateMap.get("Fighter_Id"),
                playerDataUpdateMap.get("Fighter_Name"),
                playerDataUpdateMap.get("Status"),
                playerDataUpdateMap.get("Trains_At"),
                playerDataUpdateMap.get("Fighting_Style"),
                playerDataUpdateMap.get("Height"),
                playerDataUpdateMap.get("Weight"),
                playerDataUpdateMap.get("Leg_Reach"),
                playerDataUpdateMap.get("Reach"));
    }

    public void addRowUfcFight(Table fightTable, Map<String, String> fightDataUpdateMap) throws IOException {
        //System.out.println("fightTable " + fightTable);
        System.out.println("fight " + fightDataUpdateMap.get("Fight_Id"));
        fightTable.addRow(
                fightDataUpdateMap.get("Fight_Id"),
                fightDataUpdateMap.get("Event_Id"),
                fightDataUpdateMap.get("Referee"),
                fightDataUpdateMap.get("Weight_Class"),
                fightDataUpdateMap.get("Red_Fighter_Id"),
                fightDataUpdateMap.get("Blue_Fighter_Id"),
                "1",
"3",//                fightDataUpdateMap.get("Red_Round1_Grappling_Submissions_Attempted"),
"5",//                fightDataUpdateMap.get("Red_Round1_Grappling_Takedowns_Attempted"),
"6",//                fightDataUpdateMap.get("Red_Round1_Grappling_Reversals_Landed"),
"8",//                fightDataUpdateMap.get("Red_Round1_Grappling_Standups_Landed"),
"9",//                fightDataUpdateMap.get("Red_Round1_Grappling_Takedowns_Landed"),
"10",//                fightDataUpdateMap.get("Red_Round1_Time_Back_Control_Time"),
"11",//                fightDataUpdateMap.get("Red_Round1_Time_Clinch_Time"),
"12",//                fightDataUpdateMap.get("Red_Round1_Time_Control_Time"),
"13",//                fightDataUpdateMap.get("Red_Round1_Time_Distance_Time"),
"14",//                fightDataUpdateMap.get("Red_Round1_Time_Ground_Control_Time"),
"15",//                fightDataUpdateMap.get("Red_Round1_Time_Ground_Time"),
"16",//                fightDataUpdateMap.get("Red_Round1_Time_Guard_Control_Time"),
"17",//                fightDataUpdateMap.get("Red_Round1_Time_Half_Guard_Control_Time"),
"18",//                fightDataUpdateMap.get("Red_Round1_Time_Misc_Ground_Control_Time"),
"19",//                fightDataUpdateMap.get("Red_Round1_Time_Mount_Control_Time"),
"20",//                fightDataUpdateMap.get("Red_Round1_Time_Neutral_Time"),
"21",//                fightDataUpdateMap.get("Red_Round1_Time_Side_Control_Time"),
"22",//                fightDataUpdateMap.get("Red_Round1_Time_Standing_Time"),
"23",//                fightDataUpdateMap.get("Red_Round1_Striking_BodySigStrikesLanded"),
"24",//                fightDataUpdateMap.get("Red_Round1_Striking_BodyTotalStrikesLanded"),
"25",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchBodyStrikesLanded"),
"26",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchHeadStrikesLanded"),
"27",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchLegStrikesLanded"),
"28",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchSigKicksLanded"),
"29",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchSigPunchesLanded"),
"30",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchTotalStrikesLanded"),
"31",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchSigStrikesLanded"),
"32",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceBodyKicksLanded"),
"33",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceBodyPunchesLanded"),
"34",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceBodyStrikesLanded"),
"35",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceHeadKicksLanded"),
"36",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceHeadPunchesLanded"),
"37",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceHeadStrikesLanded"),
"38",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceLegKicksLanded"),
"39",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceLegStrikesLanded"),
"40",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceStrikesLanded"),
"41",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundBodyStrikesLanded"),
"42",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundHeadStrikesLanded"),
"43",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundLegStrikesLanded"),
"44",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundSignificantKicksLanded"),
"45",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundSignificantPunchesLanded"),
"46",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundSignificantStrikesLanded"),
"47",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundTotalStrikesLanded"),
"48",//                fightDataUpdateMap.get("Red_Round1_Striking_HeadSignificantStrikesLanded"),
"49",//                fightDataUpdateMap.get("Red_Round1_Striking_HeadTotalStrikesLanded"),
"50",//                fightDataUpdateMap.get("Red_Round1_Striking_KicksLanded"),
"51",//                fightDataUpdateMap.get("Red_Round1_Striking_KnockdownLanded"),
"52",//                fightDataUpdateMap.get("Red_Round1_Striking_LegsSignificantStrikesLanded"),
"53",//                fightDataUpdateMap.get("Red_Round1_Striking_LegsTotalStrikesLanded"),
"54",//                fightDataUpdateMap.get("Red_Round1_Striking_PunchesLanded"),
"55",//                fightDataUpdateMap.get("Red_Round1_Striking_SignificantStrikesLanded"),
"56",//                fightDataUpdateMap.get("Red_Round1_Striking_TotalStrikesLanded"),
"57",//                fightDataUpdateMap.get("Red_Round1_Striking_BodySigStrikesAttempted"),
"58",//                fightDataUpdateMap.get("Red_Round1_Striking_BodyTotalStrikesAttempted"),
"59",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchBodyStrikesAttempted"),
"60",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchHeadStrikesAttempted"),
"61",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchLegStrikesAttempted"),
"62",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchSigKicksAttempted"),
"63",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchSigPunchesAttempted"),
"64",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchTotalStrikesAttempted"),
"65",//                fightDataUpdateMap.get("Red_Round1_Striking_ClinchSigStrikesAttempted"),
"66",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceBodyKicksAttempted"),
"67",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceBodyPunchesAttempted"),
"68",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceBodyStrikesAttempted"),
"69",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceHeadKicksAttempted"),
"70",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceHeadPunchesAttempted"),
"71",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceHeadStrikesAttempted"),
"72",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceLegKicksAttempted"),
"73",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceLegStrikesAttempted"),
"74",//                fightDataUpdateMap.get("Red_Round1_Striking_DistanceStrikesAttempted"),
"75",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundBodyStrikesAttempted"),
"76",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundHeadStrikesAttempted"),
"77",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundLegStrikesAttempted"),
"78",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundSignificantKicksAttempted"),
"79",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundSignificantPunchesAttempted"),
"80",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundSignificantStrikesAttempted"),
"81",//                fightDataUpdateMap.get("Red_Round1_Striking_GroundTotalStrikesAttempted"),
"82",//                fightDataUpdateMap.get("Red_Round1_Striking_HeadSignificantStrikesAttempted"),
"83",//                fightDataUpdateMap.get("Red_Round1_Striking_HeadTotalStrikesAttempted"),
"84",//                fightDataUpdateMap.get("Red_Round1_Striking_KicksAttempted"),
"86",//                fightDataUpdateMap.get("Red_Round1_Striking_LegsSignificantStrikesAttempted"),
"87",//                fightDataUpdateMap.get("Red_Round1_Striking_LegsTotalStrikesAttempted"),
"88",//                fightDataUpdateMap.get("Red_Round1_Striking_PunchesAttempted"),
"89",//                fightDataUpdateMap.get("Red_Round1_Striking_SignificantStrikesAttempted"),
"90");//                fightDataUpdateMap.get("Red_Round1_Striking_TotalStrikesAttempted"));

//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                "1",
//                fightDataUpdateMap.get("Blue_Round1_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Blue_Round1_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Blue_Round1_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Blue_Round1_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Blue_Round1_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Distance_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Ground_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Time_Standing_Time"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round1_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                "2",
//                fightDataUpdateMap.get("Red_Round2_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Red_Round2_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Red_Round2_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Red_Round2_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Red_Round2_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Red_Round2_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Distance_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Ground_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Red_Round2_Time_Standing_Time"),
//                fightDataUpdateMap.get("Red_Round2_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round2_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round2_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                "2",
//                fightDataUpdateMap.get("Blue_Round2_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Blue_Round2_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Blue_Round2_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Blue_Round2_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Blue_Round2_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Distance_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Ground_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Time_Standing_Time"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round2_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                "3",
//                fightDataUpdateMap.get("Red_Round3_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Red_Round3_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Red_Round3_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Red_Round3_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Red_Round3_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Red_Round3_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Distance_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Ground_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Red_Round3_Time_Standing_Time"),
//                fightDataUpdateMap.get("Red_Round3_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round3_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round3_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                "3",
//                fightDataUpdateMap.get("Blue_Round3_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Blue_Round3_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Blue_Round3_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Blue_Round3_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Blue_Round3_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Distance_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Ground_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Time_Standing_Time"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round3_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                "4",
//                fightDataUpdateMap.get("Red_Round4_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Red_Round4_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Red_Round4_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Red_Round4_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Red_Round4_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Red_Round4_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Distance_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Ground_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Red_Round4_Time_Standing_Time"),
//                fightDataUpdateMap.get("Red_Round4_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round4_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round4_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                "4",
//                fightDataUpdateMap.get("Blue_Round4_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Blue_Round4_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Blue_Round4_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Blue_Round4_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Blue_Round4_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Distance_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Ground_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Time_Standing_Time"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round4_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                "5",
//                fightDataUpdateMap.get("Red_Round5_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Red_Round5_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Red_Round5_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Red_Round5_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Red_Round5_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Red_Round5_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Distance_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Ground_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Red_Round5_Time_Standing_Time"),
//                fightDataUpdateMap.get("Red_Round5_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Red_Round5_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Red_Round5_Striking_TotalStrikesAttempted"));
//
//        fightTable.addRow(
//                fightDataUpdateMap.get("Fight_Id"),
//                fightDataUpdateMap.get("Event_Id"),
//                fightDataUpdateMap.get("Referee"),
//                fightDataUpdateMap.get("Weight_Class"),
//                fightDataUpdateMap.get("Blue_Fighter_Id"),
//                fightDataUpdateMap.get("Red_Fighter_Id"),
//                "5",
//                fightDataUpdateMap.get("Blue_Round5_Grappling_Submissions_Attempted"),
//                fightDataUpdateMap.get("Blue_Round5_Grappling_Takedowns_Attempted"),
//                fightDataUpdateMap.get("Blue_Round5_Grappling_Reversals_Landed"),
//                fightDataUpdateMap.get("Blue_Round5_Grappling_Standups_Landed"),
//                fightDataUpdateMap.get("Blue_Round5_Grappling_Takedowns_Landed"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Back_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Clinch_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Distance_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Ground_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Half_Guard_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Misc_Ground_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Mount_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Neutral_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Side_Control_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Time_Standing_Time"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_BodySigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_BodyTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchSigKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchSigPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchSigStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceBodyKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceBodyPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceHeadKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceHeadPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceLegKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundBodyStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundHeadStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundLegStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundSignificantKicksLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundSignificantPunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_HeadSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_HeadTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_KicksLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_KnockdownLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_LegsSignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_LegsTotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_PunchesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_SignificantStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_TotalStrikesLanded"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_BodySigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_BodyTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchSigKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchSigPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_ClinchSigStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceBodyKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceBodyPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceHeadKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceHeadPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceLegKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_DistanceStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundBodyStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundHeadStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundLegStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundSignificantKicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundSignificantPunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_GroundTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_HeadSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_HeadTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_KicksAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_LegsSignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_LegsTotalStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_PunchesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_SignificantStrikesAttempted"),
//                fightDataUpdateMap.get("Blue_Round5_Striking_TotalStrikesAttempted"));
    }

    public void addRowUfcEvent(Table eventTable, Map<String, String> eventDataUpdateMap) throws IOException {
            System.out.println("event " + eventDataUpdateMap.get("Event_Id"));
            eventTable.addRow(
                    eventDataUpdateMap.get("Event_Id"),
                    eventDataUpdateMap.get("Event_Time"),
                    eventDataUpdateMap.get("Event_City"),
                    eventDataUpdateMap.get("Event_Country"),
                    eventDataUpdateMap.get("Event_Venue"));
    }

    public void addRowNflEvent(Table eventTable, Map<String, String> eventDataUpdateMap) throws IOException{
        eventTable.addRow(eventDataUpdateMap.get("Game_Id"),
                          eventDataUpdateMap.get("Game_Date"),
                          eventDataUpdateMap.get("Game_Name"));
    }

    public void addRowNflPlays(Table playTable, Map<String, String> playDataUpdateMap) throws IOException {
        playTable.addRow(playDataUpdateMap.get("Game_Detail"),
        playDataUpdateMap.get("Year"),
        playDataUpdateMap.get("Week"),
        playDataUpdateMap.get("Date"),
        playDataUpdateMap.get("Home_Team"),
        playDataUpdateMap.get("Visitor_Team"),
        playDataUpdateMap.get("Clock_Time"),
        playDataUpdateMap.get("Play_Clock"),
        playDataUpdateMap.get("Quarter"),
        playDataUpdateMap.get("Down"),
        playDataUpdateMap.get("Yards_To_Go"),
        playDataUpdateMap.get("Yards_To_Goal"),
        playDataUpdateMap.get("Possession_Team"),
        playDataUpdateMap.get("Defensive_Team"),



        playDataUpdateMap.get("Primary_Offensive_Player"),
        playDataUpdateMap.get("Secondary_Offensive_Player"),
        playDataUpdateMap.get("Primary_Tackler"),
        playDataUpdateMap.get("Secondary_Tackler"),
        playDataUpdateMap.get("Primary_Kicker"),
        playDataUpdateMap.get("Primary_Kick_Blocker"),
        playDataUpdateMap.get("Primary_Pass_Defender"),
        playDataUpdateMap.get("Secondary_Pass_Defender"),
        playDataUpdateMap.get("Primary_Pass_Intercepter"),
        playDataUpdateMap.get("Primary_Qb_Hitter"),
        playDataUpdateMap.get("Primary_Forced_Fumbler"),
        playDataUpdateMap.get("Penalty_Player"),
        playDataUpdateMap.get("Penalty_Team_Against"),


        playDataUpdateMap.get("Play_Type"),
        playDataUpdateMap.get("Scoring_Play_Type"),
        playDataUpdateMap.get("Play_Detail_Type"),
        playDataUpdateMap.get("Yards"),
        playDataUpdateMap.get("Air_Yards"),
        playDataUpdateMap.get("Yards_After_Catch"),
        playDataUpdateMap.get("Kick_Yards"),
        playDataUpdateMap.get("Penalty_Yards"),

        playDataUpdateMap.get("Penalty_OnPlay"),
        playDataUpdateMap.get("Penalty_NoPlay"),
        playDataUpdateMap.get("Play_Deleted"),
        playDataUpdateMap.get("Scoring_Play"),
        playDataUpdateMap.get("Pass_Incomplete"),
        playDataUpdateMap.get("Pass_Intercepted"),
        playDataUpdateMap.get("Fumbled"),
        playDataUpdateMap.get("Fumble_Lost"),
        playDataUpdateMap.get("Touchdown"),
        playDataUpdateMap.get("Defensive_Touchdown"),
        playDataUpdateMap.get("Field_Goal"),
        playDataUpdateMap.get("Field_Goal_Missed"),
        playDataUpdateMap.get("Field_Goal_Blocked"),
        playDataUpdateMap.get("Punt_Blocked"),
        playDataUpdateMap.get("Extra_Point"),
        playDataUpdateMap.get("Extra_Point_Missed"),
        playDataUpdateMap.get("Extra_Point_Blocked"),
        playDataUpdateMap.get("Two_Point_Conversion"),
        playDataUpdateMap.get("Two_Point_Conversion_Failed"),
        playDataUpdateMap.get("Safety"),

        playDataUpdateMap.get("Home_Score"),
        playDataUpdateMap.get("Visitor_Score"),
        playDataUpdateMap.get("Score_Diff"));
    }

    public void addRowFantasyBaseballSuperAuto (Table rosterTable,
                                           Map<String, String> playerDataUpdateMap)
       throws IOException
    {

        rosterTable.addRow(
           playerDataUpdateMap.get("OP"),
           playerDataUpdateMap.get("#"),
           playerDataUpdateMap.get("Name"),
           playerDataUpdateMap.get("MLB Id"),
           playerDataUpdateMap.get("Team"),
           playerDataUpdateMap.get("Hand"),
           playerDataUpdateMap.get("Position"),
           playerDataUpdateMap.get("Age"),
           playerDataUpdateMap.get("Owner"),
           playerDataUpdateMap.get("Price"),
           playerDataUpdateMap.get("Contract"),
           playerDataUpdateMap.get("BP Rank"),
           playerDataUpdateMap.get("FG Rank"),
           playerDataUpdateMap.get("MLB Overall Rank"),
           playerDataUpdateMap.get("MLB Organizational Rank"),
           playerDataUpdateMap.get("Platoon"),
           playerDataUpdateMap.get("YTD PA Left"),
           playerDataUpdateMap.get("YTD SO% Left"),
           playerDataUpdateMap.get("YTD BB% Left"),
           playerDataUpdateMap.get("YTD xBA Left"),
           playerDataUpdateMap.get("YTD xISO Left"),
           playerDataUpdateMap.get("YTD Contact Left"),
           playerDataUpdateMap.get("YTD Overall Left"),
           playerDataUpdateMap.get("3Month PA Left"),
           playerDataUpdateMap.get("3Month SO% Left"),
           playerDataUpdateMap.get("3Month BB% Left"),
           playerDataUpdateMap.get("3Month xBA Left"),
           playerDataUpdateMap.get("3Month xISO Left"),
           playerDataUpdateMap.get("3Month Contact Left"),
           playerDataUpdateMap.get("3Month Overall Left"),
           playerDataUpdateMap.get("6Week PA Left"),
           playerDataUpdateMap.get("6Week SO% Left"),
           playerDataUpdateMap.get("6Week BB% Left"),
           playerDataUpdateMap.get("6Week xBA Left"),
           playerDataUpdateMap.get("6Week xISO Left"),
           playerDataUpdateMap.get("6Week Contact Left"),
           playerDataUpdateMap.get("6Week Overall Left"),
           playerDataUpdateMap.get("2Week PA Left"),
           playerDataUpdateMap.get("2Week SO% Left"),
           playerDataUpdateMap.get("2Week BB% Left"),
           playerDataUpdateMap.get("2Week xBA Left"),
           playerDataUpdateMap.get("2Week xISO Left"),
           playerDataUpdateMap.get("2Week Contact Left"),
           playerDataUpdateMap.get("2Week Overall Left"),
           playerDataUpdateMap.get("YTD PA Right"),
           playerDataUpdateMap.get("YTD SO% Right"),
           playerDataUpdateMap.get("YTD BB% Right"),
           playerDataUpdateMap.get("YTD xBA Right"),
           playerDataUpdateMap.get("YTD xISO Right"),
           playerDataUpdateMap.get("YTD Contact Right"),
           playerDataUpdateMap.get("YTD Overall Right"),
           playerDataUpdateMap.get("3Month PA Right"),
           playerDataUpdateMap.get("3Month SO% Right"),
           playerDataUpdateMap.get("3Month BB% Right"),
           playerDataUpdateMap.get("3Month xBA Right"),
           playerDataUpdateMap.get("3Month xISO Right"),
           playerDataUpdateMap.get("3Month Contact Right"),
           playerDataUpdateMap.get("3Month Overall Right"),
           playerDataUpdateMap.get("6Week PA Right"),
           playerDataUpdateMap.get("6Week SO% Right"),
           playerDataUpdateMap.get("6Week BB% Right"),
           playerDataUpdateMap.get("6Week xBA Right"),
           playerDataUpdateMap.get("6Week xISO Right"),
           playerDataUpdateMap.get("6Week Contact Right"),
           playerDataUpdateMap.get("6Week Overall Right"),
           playerDataUpdateMap.get("2Week PA Right"),
           playerDataUpdateMap.get("2Week SO% Right"),
           playerDataUpdateMap.get("2Week BB% Right"),
           playerDataUpdateMap.get("2Week xBA Right"),
           playerDataUpdateMap.get("2Week xISO Right"),
           playerDataUpdateMap.get("2Week Contact Right"),
           playerDataUpdateMap.get("2Week Overall Right"),
           playerDataUpdateMap.get("YTD PA Left Quality"),
           playerDataUpdateMap.get("YTD SO% Left Quality"),
           playerDataUpdateMap.get("YTD BB% Left Quality"),
           playerDataUpdateMap.get("YTD xBA Left Quality"),
           playerDataUpdateMap.get("YTD xISO Left Quality"),
           playerDataUpdateMap.get("YTD Contact Left Quality"),
           playerDataUpdateMap.get("YTD Overall Left Quality"),
           playerDataUpdateMap.get("3Month PA Left Quality"),
           playerDataUpdateMap.get("3Month SO% Left Quality"),
           playerDataUpdateMap.get("3Month BB% Left Quality"),
           playerDataUpdateMap.get("3Month xBA Left Quality"),
           playerDataUpdateMap.get("3Month xISO Left Quality"),
           playerDataUpdateMap.get("3Month Contact Left Quality"),
           playerDataUpdateMap.get("3Month Overall Left Quality"),
           playerDataUpdateMap.get("6Week PA Left Quality"),
           playerDataUpdateMap.get("6Week SO% Left Quality"),
           playerDataUpdateMap.get("6Week BB% Left Quality"),
           playerDataUpdateMap.get("6Week xBA Left Quality"),
           playerDataUpdateMap.get("6Week xISO Left Quality"),
           playerDataUpdateMap.get("6Week Contact Left Quality"),
           playerDataUpdateMap.get("6Week Overall Left Quality"),
           playerDataUpdateMap.get("2Week PA Left Quality"),
           playerDataUpdateMap.get("2Week SO% Left Quality"),
           playerDataUpdateMap.get("2Week BB% Left Quality"),
           playerDataUpdateMap.get("2Week xBA Left Quality"),
           playerDataUpdateMap.get("2Week xISO Left Quality"),
           playerDataUpdateMap.get("2Week Contact Left Quality"),
           playerDataUpdateMap.get("2Week Overall Left Quality"),
           playerDataUpdateMap.get("YTD PA Right Quality"),
           playerDataUpdateMap.get("YTD SO% Right Quality"),
           playerDataUpdateMap.get("YTD BB% Right Quality"),
           playerDataUpdateMap.get("YTD xBA Right Quality"),
           playerDataUpdateMap.get("YTD xISO Right Quality"),
           playerDataUpdateMap.get("YTD Contact Right Quality"),
           playerDataUpdateMap.get("YTD Overall Right Quality"),
           playerDataUpdateMap.get("3Month PA Right Quality"),
           playerDataUpdateMap.get("3Month SO% Right Quality"),
           playerDataUpdateMap.get("3Month BB% Right Quality"),
           playerDataUpdateMap.get("3Month xBA Right Quality"),
           playerDataUpdateMap.get("3Month xISO Right Quality"),
           playerDataUpdateMap.get("3Month Contact Right Quality"),
           playerDataUpdateMap.get("3Month Overall Right Quality"),
           playerDataUpdateMap.get("6Week PA Right Quality"),
           playerDataUpdateMap.get("6Week SO% Right Quality"),
           playerDataUpdateMap.get("6Week BB% Right Quality"),
           playerDataUpdateMap.get("6Week xBA Right Quality"),
           playerDataUpdateMap.get("6Week xISO Right Quality"),
           playerDataUpdateMap.get("6Week Contact Right Quality"),
           playerDataUpdateMap.get("6Week Overall Right Quality"),
           playerDataUpdateMap.get("2Week PA Right Quality"),
           playerDataUpdateMap.get("2Week SO% Right Quality"),
           playerDataUpdateMap.get("2Week BB% Right Quality"),
           playerDataUpdateMap.get("2Week xBA Right Quality"),
           playerDataUpdateMap.get("2Week xISO Right Quality"),
           playerDataUpdateMap.get("2Week Contact Right Quality"),
           playerDataUpdateMap.get("2Week Overall Right Quality"));
    }
}
